-- Agregar categoría Manga
INSERT INTO `sysapp_categoria` (`id`, `nombre`, `descripcion`, `fecha_creacion`) VALUES
(13, 'Manga', 'Los mangas son historietas o cómics originarios de Japón que se caracteriza por su narrativa visual detallada y emocionante. Cada manga cuenta historias fascinantes que van desde aventuras épicas hasta historias de romance y drama. En nuestra tienda encontrarás una amplia selección de mangas de series populares como Jujutsu Kaisen, Kimetsu no Yaiba, One Piece, My Hero Academia y muchas más. Los mangas son perfectos para coleccionistas, fanáticos del anime y personas que disfrutan de la lectura de historietas. Son ideales para sumergirte en mundos imaginarios y vivir aventuras increíbles junto a tus personajes favoritos.', NOW());

-- Agregar 10 productos de Manga populares
INSERT INTO `sysapp_producto` (`titulo`, `precio`, `foto`, `stock`, `categoria_id`, `descripcion`) VALUES
('Jujutsu Kaisen Tomo 1', 8990, 'productos/jujutsu_kaisen_1.jpg', 25, 13, 'Primer volumen del emocionante manga Jujutsu Kaisen. Acompaña a Yuji Itadori en el comienzo de su viaje en la escuela de jujutsu. Con un arte impresionante y una trama emocionante, este manga ha cautivado a millones de lectores alrededor del mundo. Descubre la magia de las técnicas de jujutsu y los personajes únicos de esta serie. Idioma: Español. Páginas: 200 aprox.'),
('Kimetsu no Yaiba Tomo 1', 8990, 'productos/kimetsu_1.jpg', 20, 13, 'El primer volumen de Demon Slayer (Kimetsu no Yaiba), la historia de Tanjiro Kamado y su viaje para encontrar una cura para su hermana transformada en demonio. Este manga combina acción intensa, personajes memorables y un mundo fascinante. Perfectamente ilustrado con detalles increíbles. Idioma: Español. Páginas: 200 aprox.'),
('One Piece Tomo 1', 9990, 'productos/one_piece_1.jpg', 30, 13, 'Comienza la aventura épica con Monkey D. Luffy en busca del tesoro más grande del mundo. Este es el primer volumen de la serie más vendida de manga de todos los tiempos. Lleno de aventura, humor, amistad y acción espectacular. Acompaña a Luffy y su tripulación en su viaje hacia el Grand Line. Idioma: Español. Páginas: 200 aprox.'),
('My Hero Academia Tomo 1', 8990, 'productos/mha_1.jpg', 22, 13, 'El primer volumen de My Hero Academia, donde conoces a Deku y su sueño de convertirse en un héroe en un mundo lleno de superhéroes. Una historia inspiradora sobre el esfuerzo, la amistad y la superación personal. Con ilustraciones dinámicas y emocionantes batallas. Idioma: Español. Páginas: 200 aprox.'),
('Attack on Titan Tomo 1', 8990, 'productos/aot_1.jpg', 18, 13, 'El primer volumen del fenómeno mundial Attack on Titan (Shingeki no Kyojin). Una historia épica sobre la lucha por la supervivencia contra titanes gigantescos. Este manga ha revolucionado la industria con su trama envolvente y giros inesperados. Prepárate para ser sorprendido. Idioma: Español. Páginas: 200 aprox.'),
('Naruto Tomo 1', 9990, 'productos/naruto_1.jpg', 25, 13, 'El inicio de la legendaria serie Naruto, donde conoces a Naruto Uzumaki y su meta de convertirse en Hokage. Este manga clásico ha inspirado a millones de fans alrededor del mundo. Una historia de ninjas, amistad, sacrificio y determinación. Ilustraciones espectaculares. Idioma: Español. Páginas: 200 aprox.'),
('Tokyo Ghoul Tomo 1', 8990, 'productos/tokyo_ghoul_1.jpg', 16, 13, 'El primer volumen de Tokyo Ghoul, una historia oscura y emocionante sobre un mundo secreto de ghouls en Tokio. Acompaña a Kaneki Ken en su transformación y su lucha por sobrevivir. Un manga psicológico con arte oscuro y atmósfera inquietante. Idioma: Español. Páginas: 200 aprox.'),
('Chainsaw Man Tomo 1', 8990, 'productos/chainsaw_man_1.jpg', 21, 13, 'El primer volumen del éxito reciente Chainsaw Man. Una historia única sobre Tanjiro Denji y su poder de convertir su cuerpo en una sierra de cadena. Acción explosiva, humor y drama se combinan en esta serie. Arte dinámico y personajes carismáticos. Idioma: Español. Páginas: 200 aprox.'),
('Bleach Tomo 1', 9990, 'productos/bleach_1.jpg', 19, 13, 'El comienzo de la épica serie Bleach, donde Ichigo Kurosaki gana el poder de ver y combatir a los espíritus. Sumergete en el mundo del Soul Society y las Soul Reapers. Un manga clásico con combates espectaculares y desarrollo de personajes memorables. Idioma: Español. Páginas: 200 aprox.'),
('Death Note Tomo 1', 9990, 'productos/death_note_1.jpg', 23, 13, 'El primer volumen del thriller psicológico Death Note. Light Yagami descubre un cuaderno misterioso que puede matar a cualquiera cuyo nombre escriba en él. Comienza un juego de gato y ratón entre Light y L. Un manga inteligente, oscuro y completamente adictivo. Idioma: Español. Páginas: 200 aprox.');
