# Generated by Django 5.2.6 on 2025-11-15 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysApp', '0002_carrito_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='usuario',
        ),
    ]
