# Generated by Django 5.2.6 on 2025-11-22 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysApp', '0006_pedido_itempedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('tipo', models.CharField(choices=[('pedido_creado', 'Pedido Creado'), ('pedido_pagado', 'Pedido Pagado'), ('pedido_procesando', 'Pedido en Procesamiento'), ('pedido_listo', 'Pedido Listo para Recoger'), ('pedido_rechazado', 'Pedido Rechazado'), ('pedido_cancelado', 'Pedido Cancelado'), ('stock_bajo', 'Stock Bajo'), ('pago_fallido', 'Pago Fallido')], max_length=50, verbose_name='Tipo de Notificación')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='sysApp.pedido', verbose_name='Pedido Relacionado')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='sysApp.producto', verbose_name='Producto Relacionado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
