# Generated by Django 5.2.6 on 2025-11-22 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysApp', '0007_notificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear_producto', 'Crear Producto'), ('editar_producto', 'Editar Producto'), ('eliminar_producto', 'Eliminar Producto'), ('actualizar_stock', 'Actualizar Stock'), ('cambiar_estado_pedido', 'Cambiar Estado de Pedido'), ('crear_categoria', 'Crear Categoría'), ('editar_categoria', 'Editar Categoría'), ('eliminar_categoria', 'Eliminar Categoría'), ('otro', 'Otra Acción')], max_length=50, verbose_name='Tipo de Acción')),
                ('modelo', models.CharField(choices=[('Producto', 'Producto'), ('Pedido', 'Pedido'), ('Categoria', 'Categoría'), ('ItemPedido', 'Item de Pedido'), ('otro', 'Otro')], max_length=50, verbose_name='Modelo Afectado')),
                ('objeto_id', models.IntegerField(help_text='ID del objeto que fue modificado', verbose_name='ID del Objeto')),
                ('descripcion', models.TextField(help_text='Descripción detallada de la acción', verbose_name='Descripción')),
                ('cambios', models.JSONField(blank=True, default=dict, help_text='Diferencias antes/después en formato JSON', verbose_name='Cambios')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Acción')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Admin')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', '-fecha_creacion'], name='sysApp_audi_usuario_730cf8_idx'), models.Index(fields=['modelo', 'objeto_id'], name='sysApp_audi_modelo_cbd992_idx')],
            },
        ),
    ]
