# Generated by Django 5.2.6 on 2025-11-27 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysApp', '0008_auditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_maximo',
            field=models.IntegerField(default=50, verbose_name='Stock Máximo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=5, verbose_name='Stock Mínimo'),
        ),
        migrations.CreateModel(
            name='AuditoriaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_auditoria', models.CharField(max_length=50, unique=True, verbose_name='Número de Auditoría')),
                ('tipo', models.CharField(choices=[('total', 'Auditoría Total'), ('categoria', 'Por Categoría'), ('producto', 'Productos Específicos'), ('ciclico', 'Inventario Cíclico')], default='ciclico', max_length=20, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sysApp.categoria', verbose_name='Categoría (si aplica)')),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_creadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Inventario',
                'verbose_name_plural': 'Auditorías de Inventario',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_sistema', models.IntegerField(verbose_name='Stock en Sistema')),
                ('stock_fisico', models.IntegerField(verbose_name='Stock Físico Contado')),
                ('diferencia', models.IntegerField(verbose_name='Diferencia')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('ajustado', models.BooleanField(default=False, verbose_name='¿Se Ajustó?')),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sysApp.auditoriainventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysApp.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Auditoría',
                'verbose_name_plural': 'Detalles de Auditoría',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada (Compra)'), ('salida_venta', 'Salida (Venta)'), ('salida_devolucion', 'Salida (Devolución)'), ('salida_daño', 'Salida (Producto Dañado)'), ('ajuste', 'Ajuste de Inventario')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('stock_anterior', models.IntegerField(verbose_name='Stock Anterior')),
                ('stock_posterior', models.IntegerField(verbose_name='Stock Posterior')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Movimiento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='sysApp.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=50, unique=True, verbose_name='Número de Orden')),
                ('proveedor', models.CharField(max_length=100, verbose_name='Proveedor')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('enviada', 'Enviada'), ('recibida', 'Recibida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_entrega_esperada', models.DateField(verbose_name='Fecha de Entrega Esperada')),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción Real')),
                ('total_estimado', models.IntegerField(verbose_name='Total Estimado (CLP)')),
                ('total_real', models.IntegerField(blank=True, null=True, verbose_name='Total Real (CLP)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField(verbose_name='Cantidad Solicitada')),
                ('cantidad_recibida', models.IntegerField(default=0, verbose_name='Cantidad Recibida')),
                ('precio_unitario', models.IntegerField(verbose_name='Precio Unitario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysApp.producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sysApp.ordencompra')),
            ],
            options={
                'verbose_name': 'Detalle de Orden de Compra',
                'verbose_name_plural': 'Detalles de Órdenes de Compra',
            },
        ),
    ]
