# Generated by Django 5.2.6 on 2025-11-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysApp', '0009_producto_stock_maximo_producto_stock_minimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('procesando', 'Listo para Recoger'), ('recogido', 'Recogido'), ('entregado', 'Entregado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado del Pago'),
        ),
    ]
