# Generated by Django 5.2.6 on 2025-12-04 20:54

from django.db import migrations


def migrate_pedido_states(apps, schema_editor):
    """Migrar estados de pedidos de aprobado->en_preparacion y procesando->listo"""
    Pedido = apps.get_model('sysApp', 'Pedido')
    
    # Cambiar 'aprobado' a 'en_preparacion'
    Pedido.objects.filter(estado='aprobado').update(estado='en_preparacion')
    
    # Cambiar 'procesando' a 'listo'
    Pedido.objects.filter(estado='procesando').update(estado='listo')


def reverse_migrate_pedido_states(apps, schema_editor):
    """Revertir los cambios de estados"""
    Pedido = apps.get_model('sysApp', 'Pedido')
    
    # Cambiar 'en_preparacion' de vuelta a 'aprobado'
    Pedido.objects.filter(estado='en_preparacion').update(estado='aprobado')
    
    # Cambiar 'listo' de vuelta a 'procesando'
    Pedido.objects.filter(estado='listo').update(estado='procesando')


class Migration(migrations.Migration):

    dependencies = [
        ('sysApp', '0012_alter_pedido_estado'),
    ]

    operations = [
        migrations.RunPython(migrate_pedido_states, reverse_migrate_pedido_states),
    ]
