# Generated by Django 5.2.6 on 2025-12-04 21:00

from django.db import migrations


def update_notification_messages(apps, schema_editor):
    """Actualizar mensajes de notificaciones antiguas de tipo pedido_pagado"""
    Notificacion = apps.get_model('sysApp', 'Notificacion')
    
    # Actualizar todas las notificaciones de tipo 'pedido_pagado' con el nuevo mensaje
    Notificacion.objects.filter(tipo='pedido_pagado').update(
        mensaje='Tu pago ha sido confirmado. Tu pedido ya fue pagado y está en preparación.'
    )


def reverse_update_notification_messages(apps, schema_editor):
    """Revertir los cambios de mensajes"""
    Notificacion = apps.get_model('sysApp', 'Notificacion')
    
    # Revertir al mensaje anterior
    Notificacion.objects.filter(
        tipo='pedido_pagado',
        mensaje='Tu pago ha sido confirmado. Tu pedido ya fue pagado y está en preparación.'
    ).update(
        mensaje='Tu pago ha sido confirmado. ¡Gracias por tu compra!'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('sysApp', '0013_migrate_pedido_states'),
    ]

    operations = [
        migrations.RunPython(update_notification_messages, reverse_update_notification_messages),
    ]
