# Generated by Django 5.2.6 on 2025-12-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysApp', '0014_update_notification_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='razon_reembolso',
            field=models.TextField(blank=True, null=True, verbose_name='Razón del Reembolso'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='reembolso_parcial',
            field=models.IntegerField(default=0, verbose_name='Reembolso Parcial Realizado'),
        ),
    ]
